all:
  vars:
    ansible_user: vagrant
    system_supporters:
      - "vagrant"
  children:
    k3s:
      vars:
        k3s_cluster_domain: sslip.io
        cluster_fqdn: "{{ ansible_eth1.ipv4.address | replace('.', '-')  }}.{{ k3s_cluster_domain }}"
        KUBECONFIG: /etc/rancher/k3s/k3s.yaml
        ansible_ssh_user: "vagrant"
        k3s_release_version: v1.17.0+k3s.1
        k3s_write_kubeconfig_mode: 644
      hosts:
        k3sMinecraft:
          ansible_ssh_host: 172.17.177.11
          ansible_ssh_common_args: '-o StrictHostKeyChecking=no'
          ansible_ssh_private_key_file: /vagrant/local/.vagrant/machines/k3snode/virtualbox/private_key
          k3s_server_manifests_templates: "{{ lookup('fileglob', '{{ playbook_dir }}/../../src/maintenance/templates/manifests-initial/*.j2', wantlist=True) }}"
          minecraft_ops: nolte07,_BlueBeaver_ #e1e45a60-d375-4fea-a238-91323b5ec11d
          minecraft_whitelist: m4yl0n,sipsap90 #e1e45a60-d375-4fea-a238-91323b5ec11d
