---
- hosts: k3sMinecraft
  become: true
  environment:
    K8S_AUTH_KUBECONFIG: /etc/rancher/k3s/k3s.yaml
  tasks:

    - name: Start MC Tekton PipelineRun
      k8s:
        definition:  "{{ lookup('template', 'tekton-mc/50-run-minecraft.yml.j2') }}"
        state: present

    - firewalld:
        port: "{{ item }}"
        state: enabled
        zone: public
        permanent: yes
      notify: reloaded firewalld
      with_items:
        - "6443/tcp"
        - "443/tcp"
        - "30551/tcp" #mc port

  handlers:
    - name: restart firewalld
      become: true
      service:
        name: firewalld
        state: restarted
    - name: reloaded firewalld
      become: true
      service:
        name: firewalld
        state: reloaded
